### ISSUE TITLE
code error

### ISSUE THREAD

**Issue by veerendrab** [Trion129/Gradient-Descent-from-scratch#1]
Hi , I am new to Data science and following Siraj videos , in that I found your code as a runner up for Gradient descent challenges. 
I tried to replicate from your code and found two issues.  
1. If I call maximise function  I am getting memory error saying value from fn_deriv is exceeding the limit.  I found you are using minimize functions only . Is minimize function code correct ? then why it is not used ?
2. In AdamGD function while defining maximize and minimize function for the below line of code you have used self.momentum value is the correct , if so why we need to declare self.velocity variable?
vel_moment = self.momentum / (1 - self.beta2).

I changed the above line of code to use self.velocity value and got the value for 6.5 as ~5.83.

As mentioned earlier I am new to this and I am probably wrong .

**Comment by Trion129** [comment]
Hy,
The memory error must be because you tried to maximise the function at a infinitely rising edge. E.g. maximising at 6.5 will make it keep rising.
Thanks for the code error, I don't know how I missed that
